version: '3.8'
services:
  postgres:
    image: postgres
    container_name: execution-backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: ${POSTGRES_DATA:-/data/postgres}
    volumes:
      - postgres:${POSTGRES_DATA:-/data/postgres}
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres:
